### ISSUE TITLE
Objects teleport when used with A* search

### ISSUE THREAD

**Issue by tekier** [Bam4d/Griddly#233]
I am currently trying to create an environment where a team of agents (jellies) compete with enemy units (gnomes) to win a shootout game. The gnomes are part of the environment and make use of A* and proximity triggers to fire on the jellies. The gnomes are meant to move one block at a time, but they seem to teleport randomly across the screen.

**Reproduce**
[aliens.zip](https://github.com/Bam4d/Griddly/files/9277231/aliens.zip)

1. Unpack the zip
2. Run `aliens.py`. 

**Env**
griddly==1.4.3
Python 3.8
MacOS Monterey

**Comment by Bam4d** [comment]
I can see that your gdy is executing too many search actions, I think probably the cooldown is broken.

because each gnome is executing lots of search commands... it's moving them multiple times.

if you use print commands you can debug the states of the game and find why  `-print: [variable_name, "some text"]`
